services:
  web_service:
    build:
      context: ./web_service
    ports:
      - "8000:5000"
    depends_on:
      - postgres_service
      - redis_service
    networks:
      - app_network

  postgres_service:
    build:
      context: ./database_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_service:
    build:
      context: ./cache_service
    networks:
      - app_network
    volumes:
      - redis_data:/data
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
